// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT9a-DBT_V1Xh3u6KH937PZQuirQT8bCk',
    appId: '1:812816743651:android:07c0a35e02746b9112d9d6',
    messagingSenderId: '812816743651',
    projectId: 'quantum-shop-22',
    storageBucket: 'quantum-shop-22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxLM1xH_GSXr143iJGx4dXyBQuENqxf0E',
    appId: '1:812816743651:ios:7ab4758ab7c4260112d9d6',
    messagingSenderId: '812816743651',
    projectId: 'quantum-shop-22',
    storageBucket: 'quantum-shop-22.firebasestorage.app',
    iosBundleId: 'com.example.quantumshop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1qNCneb_mXi3R18vokzi3FXSEZHNjda8',
    appId: '1:812816743651:web:0ed30e4a1075755f12d9d6',
    messagingSenderId: '812816743651',
    projectId: 'quantum-shop-22',
    authDomain: 'quantum-shop-22.firebaseapp.com',
    storageBucket: 'quantum-shop-22.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxLM1xH_GSXr143iJGx4dXyBQuENqxf0E',
    appId: '1:812816743651:ios:7ab4758ab7c4260112d9d6',
    messagingSenderId: '812816743651',
    projectId: 'quantum-shop-22',
    storageBucket: 'quantum-shop-22.firebasestorage.app',
    iosBundleId: 'com.example.quantumshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1qNCneb_mXi3R18vokzi3FXSEZHNjda8',
    appId: '1:812816743651:web:13d509a5fdd0406c12d9d6',
    messagingSenderId: '812816743651',
    projectId: 'quantum-shop-22',
    authDomain: 'quantum-shop-22.firebaseapp.com',
    storageBucket: 'quantum-shop-22.firebasestorage.app',
  );

}